# Generated by Django 6.0.3 on 2026-04-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='humidity',
            field=models.FloatField(default=0),
        ),
    ]
